# Generated by Django 5.2.7 on 2025-10-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_telegramuser_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analyst_type', models.CharField(choices=[('EP', 'Аналитик-решала'), ('EJ', 'Аналитик-суетолог'), ('IP', 'Аналитик-вайбик'), ('IJ', 'Аналитик-стратег')], max_length=2)),
                ('analyst_name', models.CharField(max_length=255)),
                ('animal', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('ei_score', models.IntegerField()),
                ('pj_score', models.IntegerField()),
                ('gift_received', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testresult', to='users.telegramuser')),
            ],
        ),
    ]
