# Generated by Django 5.2.7 on 2025-10-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_workshop_workshopregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='time',
        ),
        migrations.AddField(
            model_name='workshop',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
