# Generated by Django 5.2.7 on 2025-10-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_workshop_time_workshop_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_expert',
            field=models.BooleanField(default=False),
        ),
    ]
