# Generated by Django 5.2.7 on 2025-10-16 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_telegramuser_is_expert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('meeting_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='users.telegramuser')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_slots', to='users.telegramuser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.consultationtopic')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('expert', 'start_time', 'end_time')},
            },
        ),
    ]
