# Generated by Django 5.2.7 on 2025-10-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_consultationtopic_consultationslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationslot',
            name='meeting_location',
        ),
        migrations.AddField(
            model_name='consultationtopic',
            name='experts',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_expert': True}, related_name='expert_topics', to='users.telegramuser'),
        ),
    ]
