# Generated by Django 5.2.7 on 2025-11-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='vacancies_interest',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
