# Generated by Django 5.2.7 on 2025-11-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_telegramuser_vacancies_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('experts', models.ManyToManyField(blank=True, limit_choices_to={'is_expert': True}, related_name='topic_time_slots', to='users.telegramuser')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.consultationtopic')),
            ],
            options={
                'ordering': ['start_time'],
                'unique_together': {('topic', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='consultationslot',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='users.topictimeslot'),
        ),
    ]
