# Generated by Django 5.2.7 on 2025-11-13 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_topictimeslot_consultationslot_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AddField(
            model_name='quizresult',
            name='quiz_date',
            field=models.DateField(db_index=True, default=datetime.date(2025, 11, 20)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizresults', to='users.telegramuser'),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('user', 'quiz_date')},
        ),
    ]
