# Generated by Django 5.2.7 on 2025-11-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_quizresult_options_quizresult_quiz_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='telegram_id',
        ),
    ]
