# Generated by Django 5.2.7 on 2025-11-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(help_text='Глобальная дата события. Используется для фильтрации консультаций (20 или 21 ноября)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки проекта',
                'verbose_name_plural': 'Настройки проекта',
            },
        ),
    ]
