# Generated by Django 5.2.7 on 2025-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_projectsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Максимальное количество участников. Если не указано, лимит не действует.', null=True),
        ),
    ]
